language: r
matrix:
  include:
    - os: linux
       r: oldrel
    - os: linux
       r: release
    - os: linux
       r: devel
    - os: osx
       r: oldrel
    - os: osx
       r: release
#r:
#- oldrel
#- release
#- devel
cache: packages
fortran: false
#os:
#- osx
#- linux
osx_image: xcode9
dist: trusty
warnings_are_errors: true
sudo: required
install:
    - R -e 'install.packages("Rcpp")'

