language: r
cache: packages
r:
- oldrel
- release
- devel
fortran: false
os:
- osx
- linux
osx_image: xcode9
dist: trusty
warnings_are_errors: true
sudo: required
install:
    - R -e 'install.packages("Rcpp")'

