language: r
warnings_are_errors: true
sudo: required
install:
  - R -e 'install.packages(c("Rcpp", "RcppArmadillo"))'
env:
  - PKG_CPPFLAGS=`Rscript -e 'install.packages(c("Rcpp", "RcppArmadillo"), repos="https://cloud.r-project.org");cat(toString(RcppArmadillo:::CxxFlags()));cat(" ");cat(toString(Rcpp:::CxxFlags()))'`

