language: r
r:
  - oldrel
  - release
  - devel
cache: packages
os:
- osx
- linux
osx_image: xcode9
dist: trusty
warnings_are_errors: true
sudo: required
install:
    - R -e 'install.packages("Rcpp")'
env:
  - PKG_CPPFLAGS="-I/home/travis/R/Library/Rcpp/include" R_BUILD_ARGS="--resave-data"
