language: r
r:
  - oldrel
  - release
  - devel
cache: packages
os:
- osx
- linux
osx_image: xcode9
dist: trusty
warnings_are_errors: true
sudo: required
install:
    - R -e 'install.packages(c("Rcpp", "RcppArmadillo"))'
env:
  - PKG_CPPFLAGS="-I/home/travis/R/Library/Rcpp/include -I/home/travis/R/Library/RcppArmadillo/include"

