language: r
cache: packages
after_success:
  - Rscript -e 'library(covr); codecov()'
matrix:
  include:
    - os: linux
      r: oldrel
      dist: bionic
      warnings_are_errors: true
      sudo: required
      fortran: false
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
    - os: linux
      r: release
      dist: bionic
      warnings_are_errors: true
      sudo: required
      fortran: false
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
    - os: linux
      r: devel
      dist: bionic
      warnings_are_errors: true
      sudo: required
      fortran: false
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
    - os: osx
      r: oldrel
      dist: bionic
      warnings_are_errors: true
      sudo: required
      fortran: false
      osx_image: xcode9
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
    - os: osx
      r: release
      dist: bionic
      warnings_are_errors: true
      sudo: required
      fortran: false
      osx_image: xcode9
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'


