language: r
warnings_are_errors: true
sudo: required
install:
  - R -e 'install.packages(c("Rcpp", "RcppArmadillo"))'
env:
  - PKG_CPPFLAGS=`Rscript -e 'Rcpp:::CxxFlags()'`:`Rscript -e 'RcppArmadillo:::CxxFlags()'`
