language: r
r:
  - oldrel
  - release
  - devel
cache: packages
os:
- osx
- linux
osx_image: xcode9
dist: trusty
warnings_are_errors: true
sudo: required
install:
    - R -e 'install.packages("Rcpp")'
<<<<<<< HEAD

=======
env:
  - R_BUILD_ARGS="--resave-data"
  #- PKG_CPPFLAGS="-I/home/travis/R/Library/Rcpp/include"
>>>>>>> 5fdb98eb97be02c56582a12109ce73a179ced17d
