language: r
matrix:
  include:
    - os: linux
      r:
        - oldrel
        - release
        - devel
    - os: osx
      r:
        - oldrel
        - release
#r:
#  - oldrel
#  - release
#  - devel
cache: packages
fortran: false
#os:
#- osx
#- linux
osx_image: xcode9
dist: trusty
warnings_are_errors: true
sudo: required
install:
    - R -e 'install.packages("Rcpp")'

