on:
  push:
    branches: [main, master]

name: R-deploy

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        artifacts: "release.tar.gz,/*"
        token: ${{ secrets.GITHUB_TOKEN }}
