on:
  push:
    branches: [main, master]

name: R-deploy

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    name: Deploy
    strategy:
      fail-fast: false
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
      - run:
          mkdir rel
          zip --junk-paths -r rel/release R data man src tests CONTRIBUTING.md DESCRIPTION LICENSE NAMESPACE README.md
      - uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.mmftp_server }}
          username: ${{ secrets.mmftp_user }}
          password: ${{ secrets.mmftp_password }}
          port: ${{ secrets.mmftp_port }}
          local-dir: ./rel/
          server-dir: ${{ secrets.mmftp_dir }}
          security: strict

