on:
  push:
    branches: [main, master]

name: R-deploy

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,/*"
        token: ${{ secrets.GITHUB_TOKEN }}
